### ISSUE TITLE
SSL cert not showing up on https://www.battleforthenet.com/

### ISSUE THREAD

**Issue by kevinzwhuang** [fightforthefuture/battleforthenet#136]
@holmesworcester 
It looks like there's a weird redirect problem on https://www.battleforthenet.com/, where it's redirecting away from the version of itself where it has an SSL cert to where it isn't secured at all.

Other battleforthenet paths seem to be unaffected. (i.e.: https://www.battleforthenet.com/teaminternet/)

![ssl_problem](https://user-images.githubusercontent.com/7256178/33400758-ecf57308-d50b-11e7-9245-a9be17c1f242.gif)

**Comment by rubbingalcoholic** [comment]
It looks like the YouTube embed includes a non secure image and this is causing the page to go into ‘mixed content’ mode, even though it’s *mostly* secure.

I would recommend removing or altering whatever is loading that image.

From: Kevin Huang
Sent: Wednesday, November 29, 2017 3:49 PM
To: fightforthefuture/battleforthenet
Cc: Subscribed
Subject: [fightforthefuture/battleforthenet] SSL cert not showing up onhttps://www.battleforthenet.com/ (#136)

@holmesworcester
It looks like there's a weird redirect problem on https://www.battleforthenet.com/, where it's redirecting away from the version of itself where it has an SSL cert to where it isn't secured at all.
Other battleforthenet paths seem to be unaffected. (i.e.: https://www.battleforthenet.com/teaminternet/)

**Comment by kevinzwhuang** [comment]
Nice catch @rubbingalcoholic, it was one of the youtube thumbnail images. Just opened PR #137 to address fix this.
