### ISSUE TITLE
Missing state for DC rep

### ISSUE THREAD

**Issue by mlinksva** [fightforthefuture/battleforthenet#191]
On /scoreboard/all DC is not an option in the dropdown and at the very bottom of the page the DC rep is under a state heading "undefined". On / the dropdown includes DC, but no information is found.

The data is being stored and retrieved a number of different ways in/by the app, but I think this problem comes down to data retrieved from data.battleforthenet.com. Specifically https://data.battleforthenet.com/politicians/dc.json is empty and in https://data.battleforthenet.com/scoreboard/all.json there's a missing state for DC:

> {"bioguide_id":"N000190","first_name":"Ralph","last_name":"Norman","call_count":685,"letter_count":null,"tweet_count":null,"cable_contributions":15050,"supports_cra":false,"twitter":"RalphNorman","district":"SC-5","party":"Republican","state":"SC","organization":"House"},
> {"bioguide_id":"N000147","first_name":"Eleanor","last_name":"Norton","call_count":1160,"letter_count":null,"tweet_count":null,"cable_contributions":null,"supports_cra":false,"twitter":"EleanorNorton","district":"DC-0","party":"Democrat","organization":"House"},

Also in https://data.battleforthenet.com/politicians.json there's a missing stateCode for DC:

> {"biocode":"G000410","name":"Green","partyCode":"d","organization":"House","state":"Texas","stateCode":"TX","yesOnCRA":false,"twitter":"RepGeneGreen","calls":636},
> {"biocode":"N000147","name":"Norton","partyCode":"d","organization":"House","state":"District of Columbia","yesOnCRA":false,"twitter":"EleanorNorton","calls":1160},

**Comment by kenmickles** [comment]
Thanks, @mlinksva! An upstream data source changed "District Of Columbia" to "District of Columbia" and broke some bad assumptions. Should be working now.
