### ISSUE TITLE
Add "protest" button to battleforthenet.com flow, ideally that passes through zipcode

### ISSUE THREAD

**Issue by holmesworcester** [fightforthefuture/battleforthenet#99]
This screen would ideally have a "protest" button in after-action-footer.tsx, like the widget does.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/213678/28136788-0282a06c-6719-11e7-8419-4749117c4961.png">

It should link to the same place as the button in the widget, and pass through the zipcode that the user has already entered in the same way.

It would look the same and use the "pin.svg" icon.

**Comment by tibetsprague** [comment]
@holmesworcester how do we pass through the zipcode?

**Comment by mikemorris** [comment]
@tibetsprague https://github.com/fightforthefuture/battleforthenet-widget/blob/master/iframe/script.js#L273-L276

**Comment by tibetsprague** [comment]
https://github.com/fightforthefuture/battleforthenet/pull/100
